WIP-Feature/135/profile view page
wizeline/remix-project-lab pull request #154
Opened 2023-05-05 22:09 UTC by LindaNayeli104

# What does this PR do?

Developed the user profile component, where the user can see their information and past projects. This information will come from GitHub.

Made the call to get the information from GitHub, built a table to store the information obtained, stored the information in the table, queried and displayed the information on the frontend.

# Where should the reviewer start?

Run the project locally and select the profile option by clicking your email in the home page navigation bar.

# How should this be manually tested?

- Go to the profile page and check if your GitHub information is displayed
	-Username
	- Projects

# What are the relevant tickets?

135, 150 and 153

# Screenshots

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2023-05-12 21:42 UTC, leslye-patino approved these changes
LGTM!

2023-05-12 21:42 UTC, leslye-patino approved these changes
LGTM!

2023-05-12 22:08 UTC, martinrobled0 requested changes

2023-05-15 16:21 UTC, LindaNayeli104 commented on app/auth.server.ts
> +        createGitHubProfile(email, userInfo.items[0].login, userInfo.items[0].avatar_url, userInfo.items[0].repos_url);
Done!

2023-05-15 16:25 UTC, martinrobled0 approved these changes
good job! lgtm

2023-05-15 16:41 UTC, merged