Feat/151/roadmap project
wizeline/remix-project-lab pull request #166
Opened 2023-06-02 22:14 UTC by martinrobled0

# What does this PR do?
Contribuitors are able to add roadmaps for their projects.

# How should this be manually tested?

- Join to one project
- Edit the project
- Select the roadmap option
- Add/edit/delete some objectives

# Any background context you want to provide?

# What are the relevant tickets?
#151 

# Screenshots
<img width="1201" alt="image" src="https://github.com/wizeline/remix-project-lab/assets/74632242/9fbf8df0-cc27-4f9e-90ae-cdce44662fc1">

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2023-06-08 19:01 UTC, juanan150 requested changes

2023-06-08 22:40 UTC, martinrobled0 commented on app/routes/projects/$projectId/roadmap.tsx
> +                        />
nice, it works 💯

2023-06-09 11:33 UTC, juanan150 approved these changes
LGTM

2023-06-19 17:31 UTC, martinrobled0 commented
For changes in the requirements we'll close this PR without merge

2023-06-19 17:31 UTC, closed without merging