Added table view
wizeline/remix-project-lab pull request #179
Opened 2023-07-03 08:36 UTC by ElenSuvarianTer

# What does this PR do?

It creates a table view for existing projects# Where should the reviewer start?

# How should this be manually tested?
In the projects view, click on the Table Icon

# Any background context you want to provide?

# What are the relevant tickets?
remix-project-lab #176:
"Have a table view for the projects, so we can see valuable information in a more structured and easy to read format"

# Screenshots

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2023-07-06 14:00 UTC, martinrobled0 commented on package-lock.json
> +        "@mui/icons-material": "^5.11.16",
why do we need that version?

2023-07-07 10:17 UTC, ElenSuvarianTer commented on package-lock.json
> +        "@mui/icons-material": "^5.11.16",
we really don't need it.

2023-07-07 10:22 UTC, ElenSuvarianTer commented on package-lock.json
> +        "@mui/icons-material": "^5.11.16",
Fixed!

2023-07-13 19:13 UTC, jackbravo requested changes

2023-07-13 19:13 UTC, jackbravo commented on package.json
> +    "@material-ui/core": "^4.12.4",
this shouldn't be necessary, we are already using mui v5.

2023-07-14 15:58 UTC, jackbravo approved these changes

2023-07-14 15:58 UTC, merged