Feat/219/allow interns view projects with mentors
wizeline/remix-project-lab pull request #227
Opened 2023-10-03 23:37 UTC by CarlosMilano

# What does this PR do?

Allow interns view only projects that have mentors

# Where should the reviewer start?

/internshipProjects/index.tsx

# How should this be manually tested?

An admin can give mentor role to a contributor, then interns can see that project, if a project doesn't have mentors, interns cant see that project

# Any background context you want to provide?

# What are the relevant tickets?

#219 

# Screenshots

![Captura de pantalla 2023-10-03 a la(s) 5 34 07 p m](https://github.com/wizeline/remix-project-lab/assets/93209499/40800d10-de5e-4663-8950-74f10678fd09)
![Captura de pantalla 2023-10-03 a la(s) 5 35 38 p m](https://github.com/wizeline/remix-project-lab/assets/93209499/d39f6281-98bc-4c4c-a126-9c35e4f680cc)
![Captura de pantalla 2023-10-03 a la(s) 5 35 51 p m](https://github.com/wizeline/remix-project-lab/assets/93209499/e216448a-04f1-4e1d-9775-503098d30ab5)
![Captura de pantalla 2023-10-03 a la(s) 5 36 13 p m](https://github.com/wizeline/remix-project-lab/assets/93209499/1694140f-ca64-4a7f-859e-0ed046209e4e)
![Captura de pantalla 2023-10-03 a la(s) 5 36 35 p m](https://github.com/wizeline/remix-project-lab/assets/93209499/e6656ee1-591d-4622-b308-ef7fd438ca29)

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2023-10-04 16:09 UTC, AxelUZ reviewed
LGTM! 👍

2023-10-04 20:40 UTC, martinrobled0 requested changes

2023-10-04 20:40 UTC, martinrobled0 commented on app/models/discipline.server.ts
> +export async function searchDisciplineName(disciplineName: string) {
why the search discipline name function hace as parameter discipline name?

2023-10-04 20:40 UTC, martinrobled0 commented on app/routes/internshipProjects/index.tsx
> +  const id = await searchDisciplineName("Mentor");
use the constants file instead use "mentor" directly

2023-10-06 17:30 UTC, martinrobled0 approved these changes

2023-10-06 17:36 UTC, merged