Feat/229/improve view of applicants postullated in projects
wizeline/remix-project-lab pull request #264
Opened 2023-11-07 18:20 UTC by AxelUZ

# What does this PR do?
Improves the way applicants are displayed in projects and extracts the profile picture from linkdin

# Where should the reviewer start?
app/routes/applicants/$applicantId/index.tsx
app/routes/projects/$projectId/index.tsx

# How should this be manually tested?
1. Log in to linkdin and fill out the form.
2. Apply to any project
3. login with google
4. Verify that the applicant's photo is displayed in /applicants.
5. Verify that the project you applied to shows the applicant correctly.

# Any background context you want to provide?

# What are the relevant tickets?
#229 

# Screenshots
<img width="1728" alt="Captura de pantalla 2023-11-07 a la(s) 8 58 40 a m" src="https://github.com/wizeline/remix-project-lab/assets/58340818/37ab9c62-49dc-4347-a09f-c9e8b11d1811">

<img width="1728" alt="Captura de pantalla 2023-11-07 a la(s) 8 58 48 a m" src="https://github.com/wizeline/remix-project-lab/assets/58340818/21c3bb08-7a9b-4442-ae5d-a631ac084fc6">

# Questions

# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2023-11-07 21:17 UTC, martinrobled0 requested changes

2023-11-07 21:17 UTC, martinrobled0 commented on app/routes/projects/$projectId/index.tsx
> +      <Container sx={{ marginBottom: 2 }}>
I think that we can do a new component based on this code in order to use it on other parts of the project

2023-11-07 21:17 UTC, martinrobled0 commented on app/routes/projects/$projectId/index.tsx
> +      <Container sx={{ marginBottom: 2 }}>
Also if there is no applicants the containers looks like this 
<img width="1169" alt="image" src="https://github.com/wizeline/remix-project-lab/assets/74632242/29745c04-babe-40e4-9213-34a647d14391">
without a card component, if you move this to a new component we can improve that

2023-11-09 17:51 UTC, maubarraganwize approved these changes
Looks and works ok to me

2023-11-09 18:15 UTC, beatriz-sanchez-wizeline approved these changes
Works for me and the Applicants section has been removed when no applicants have applied.

2023-11-09 23:48 UTC, martinrobled0 approved these changes

2023-11-09 23:49 UTC, merged