Create project functional inputs
wizeline/remix-project-lab pull request #50
Opened 2022-10-14 18:01 UTC by Andresmagic

# What does this PR do?

Migrate the simple inputs to create a project

# Where should the reviewer start?

You can start checking ProjectForm.tsx and review every input in there 

# How should this be manually tested?

1. From the landing page click the button of 'New Proposal'
2. Fill the inputs 
3. Click the 'Create Project' button 
4. Check in your terminal your inputs from the console.log

# Any background context you want to provide?

There are still some inputs that are needed to create a project that are commentated.
The TextEditor input isn't getting recognized by formData.
This PR doesn't include the useFetcher for creating the project, just the base inputs

# What are the relevant tickets?

https://github.com/wizeline/remix-project-lab/pull/48

# Screenshots
![image](https://user-images.githubusercontent.com/42359482/195907605-e09e24cd-d3e1-4855-88c0-a9e975adac6d.png)
![image](https://user-images.githubusercontent.com/42359482/195910687-70789ff5-f47f-4413-ba8e-5a453ed4f2d5.png)
![image](https://user-images.githubusercontent.com/42359482/195910817-377d3f2f-1127-4891-8b56-7446f0b89c94.png)

This PR was made with the collaboration of: @dmojarrot 
# Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2022-10-17 12:06 UTC, dmojarrot commented
Text editor input now working.

<img width="1165" alt="Screen Shot 2022-10-17 at 14 05 21" src="https://user-images.githubusercontent.com/62604183/196172853-a54f838a-ad68-4813-9268-c6dc056dfcbd.png">

<img width="591" alt="Screen Shot 2022-10-17 at 14 05 45" src="https://user-images.githubusercontent.com/62604183/196172906-891b5f49-f96a-4ba0-a7ad-244de9d791f3.png">

2022-10-17 22:28 UTC, martinrobled0 commented on app/core/components/DisciplineSelect/index.tsx
> +  size?: "small" | "medium" | undefined;
creo que ahi esta de mas el undefined

2022-10-17 22:46 UTC, martinrobled0 requested changes
just the undefined things but LGTM

2022-10-18 00:02 UTC, Andresmagic commented on app/core/components/DisciplineSelect/index.tsx
> +  size?: "small" | "medium" | undefined;
Cierto!, igual ese input aún está comentado en el ProjectForm y no es parte de los que están funcionales, pero igual lo cambio de una vez:)

2022-10-20 13:21 UTC, juanan0309 requested changes

2022-10-20 13:21 UTC, juanan0309 commented on app/core/components/ProjectOwnerField/index.tsx
> +  const profiles: readonly any[] = ["diego", "jorge", "jose"];
We shouldn't have this hardcoded, we have a `Profiles` table that help us with this info

2022-10-20 13:21 UTC, juanan0309 commented on app/core/components/RelatedProjectsSelect/index.tsx
> +  const projects = ["Project 1", "Project 2", "Project 3", "Project 4"];
We shouldn't have this hardcoded

2022-10-20 13:21 UTC, juanan0309 commented on app/core/components/SkillsSelect/index.tsx
> +  const skills = ["React", "Node", "Python", "Java", "C++", "C#"];
We shouldn't have this hardcoced

2022-10-20 13:21 UTC, juanan0309 commented on app/models/project.server.ts
> +
Is this blank space necessary?

2022-10-20 13:21 UTC, juanan0309 commented on app/routes/projects/components/ProjectForm.tsx
> +  const tiers = [{ name: "0" }, { name: "1" }, { name: "2" }, { name: "3" }];
I think this shouldn't be hardcoded

2022-10-20 15:28 UTC, Andresmagic commented on app/root.tsx
> +
I tried doing this in the create project file but I got errors that say that it should be done in the `root.tsx` . But this was just to see the console log and seeing if the formData was working, but in the end i think we're going to delete this from the root and do all with the useFetcher

2022-10-20 15:36 UTC, Andresmagic commented on app/models/project.server.ts
> +
No, ups

2022-11-09 20:17 UTC, closed without merging